In [ ]:
# Install Pandas

In [3]:
!pip install pandas

Requirement already satisfied: pandas in c:\users\windows 11-23h2\appdata\local\programs\python\python314\lib\site-packages (3.0.1)
Requirement already satisfied: numpy>=2.3.3 in c:\users\windows 11-23h2\appdata\local\programs\python\python314\lib\site-packages (from pandas) (2.4.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\windows 11-23h2\appdata\local\programs\python\python314\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\windows 11-23h2\appdata\local\programs\python\python314\lib\site-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in c:\users\windows 11-23h2\appdata\local\programs\python\python314\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

# import pandas

In [4]:
import pandas as pd

In [5]:
pd.__version__

'3.0.1'

# 1. Dataframe

In [6]:

df = pd.DataFrame([11,22,33],columns=['Col_Name'])
print(df)

   Col_Name
0        11
1        22
2        33

In [7]:
print(type(df))

<class 'pandas.DataFrame'>

In [8]:
data = {
    'Name' : ['Deepika' ,'Ekta' , 'Amit' , 'Kishor'],
    'Age'  : [16 ,17,18,19 ],
    'Salery' :  [90000 , 70000 , 50000, 30000],
}

In [9]:
df = pd.DataFrame(data)
print(df)

      Name  Age  Salery
0  Deepika   16   90000
1     Ekta   17   70000
2     Amit   18   50000
3   Kishor   19   30000

In [10]:
print(type(df))

<class 'pandas.DataFrame'>

In [11]:
df.head(2)

      Name  Age  Salery
0  Deepika   16   90000
1     Ekta   17   70000

In [12]:
df.tail(2)

     Name  Age  Salery
2    Amit   18   50000
3  Kishor   19   30000

In [13]:
df.shape

(4, 3)

In [14]:
df.rename(columns = {'Salery': 'Monthly_Salery'},inplace =True)

In [15]:
df

      Name  Age  Monthly_Salery
0  Deepika   16           90000
1     Ekta   17           70000
2     Amit   18           50000
3   Kishor   19           30000

In [16]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Name            4 non-null      str
 1   Age             4 non-null      int64
 2   Monthly_Salery  4 non-null      int64
dtypes: int64(2), str(1)
memory usage: 228.0 bytes

In [17]:
df.describe()

             Age  Monthly_Salery
count   4.000000        4.000000
mean   17.500000    60000.000000
std     1.290994    25819.888975
min    16.000000    30000.000000
25%    16.750000    45000.000000
50%    17.500000    60000.000000
75%    18.250000    75000.000000
max    19.000000    90000.000000

In [24]:
df.to_csv('Test_data.csv' , index = False) # Export Data Frame

In [19]:
load_df = pd.read_csv('Test_data.csv')  # import Data Frame
print(load_df)

      Name  Age  Monthly_Salery
0  Deepika   16           90000
1     Ekta   17           70000
2     Amit   18           50000
3   Kishor   19           30000

# Select Cloumns

In [20]:
df[['Name' , 'Monthly_Salery']]

      Name  Monthly_Salery
0  Deepika           90000
1     Ekta           70000
2     Amit           50000
3   Kishor           30000

## Select Rows

In [21]:
df.loc[df.Name=='Deepika']

      Name  Age  Monthly_Salery
0  Deepika   16           90000

In [22]:
df.iloc[(df.Name == 'Deepika') & (df.Monthly_Salery >= 50000)]

      Name  Age  Monthly_Salery
0  Deepika   16           90000

# iloc  - index-value based

In [23]:
df.iloc[0] # index based value

Name              Deepika
Age                    16
Monthly_Salery      90000
Name: 0, dtype: object

In [25]:
df.iloc[0:2]  # (start:stop:step: )

      Name  Age  Monthly_Salery
0  Deepika   16           90000
1     Ekta   17           70000

In [27]:
df.loc[0:2]

      Name  Age  Monthly_Salery
0  Deepika   16           90000
1     Ekta   17           70000
2     Amit   18           50000

# Filter Dataframe

In [28]:
df

      Name  Age  Monthly_Salery
0  Deepika   16           90000
1     Ekta   17           70000
2     Amit   18           50000
3   Kishor   19           30000

In [31]:
df['Age'] >18

0    False
1    False
2    False
3     True
Name: Age, dtype: bool

In [36]:
df[df['Age'] >=18]

     Name  Age  Monthly_Salery
2    Amit   18           50000
3  Kishor   19           30000

In [37]:
df_age_filter

     Name  Age  Monthly_Salery
2    Amit   18           50000
3  Kishor   19           30000

In [44]:
df[(df['Age'] >=18) & (df['Monthly_Salery'] >= 50000)]

   Name  Age  Monthly_Salery
2  Amit   18           50000

In [46]:
df.where(df['Age'] >=18)

     Name   Age  Monthly_Salery
0     NaN   NaN             NaN
1     NaN   NaN             NaN
2    Amit  18.0         50000.0
3  Kishor  19.0         30000.0

In [47]:
df.where(df['Age'] >=18 ,other = 'Not elegible')

           Name           Age Monthly_Salery
0  Not elegible  Not elegible   Not elegible
1  Not elegible  Not elegible   Not elegible
2          Amit            18          50000
3        Kishor            19          30000